### ISSUE TITLE
Issue when registering for events

### ISSUE THREAD

**Issue by AnshulMalik** [gawdsnitkkr/techspardha-17-backend#16]
Since we have the feature of moving participants to the next round, we must keep the current level of participant in EventRegisters table. @rewanth1997

**Comment by rewanth1997** [comment]
That will be in the events table and we can fetch from it.

**Comment by AnshulMalik** [comment]
Suppose I want to move n number of contestants to next level?

**Comment by rewanth1997** [comment]
Okay , I will add a column called currentRound in the `teams` table for `Team events`. I guess it would be fine. And for event register also i will add an attribute there. @AnshulMalik
