### ISSUE TITLE
Git workflow to be followed

### ISSUE THREAD

**Issue by AnshulMalik** [gawdsnitkkr/techspardha-17-backend#2]
1. Create a new branch
2. Do what you want in that branch
3. If ready to push, pull the master branch.
4. Merge master to the newly created branch, resolve conflict (if any).
5. Run ```npm test```, to test you didn't broke anything.
6. Push your new branch.
7. Create a pull request.

NOTE: DON'T PUSH CODE DIRECTLY TO MASTER

**Comment by rewanth1997** [comment]
That's what is exactly going on here @AnshulMalik

**Comment by AnshulMalik** [comment]
@MacBox7 didn't follow this workflow.
