### ISSUE TITLE
Google android sign in

### ISSUE THREAD

**Issue by abhik-setia** [gawdsnitkkr/techspardha-17-backend#28]
Different token is generated by android sign in
Backend is using google plus api which requires different token than android sign in api
Need to implement a different end point result.

**Comment by AnshulMalik** [comment]
@beezlebub0530 Can you please take care of the issue.

[https://developers.google.com/identity/sign-in/android/backend-auth](https://developers.google.com/identity/sign-in/android/backend-auth) 
This is what the app uses to generate token, an ID Token is generated for the app, whereas in web apps, access token is generated.

**Comment by AnshulMalik** [comment]
Merged
