### ISSUE TITLE
isNew is only returned on signup

### ISSUE THREAD

**Issue by AnshulMalik** [gawdsnitkkr/techspardha-17-backend#29]
@beezlebub0530 

Consider a scenario when user sign up with gmail then we send isNew : true. Now we ask him about interests, and he goes closes the app, without filling the interests.

On second time login, API will not return isNew at all. But we want it to return false since user's interests are not collected yet.

Issues here are:
- Return isNew on login as well
- Return false isNew until user's interests are not set

**Comment by abhik-setia** [comment]
Good point here , But we will also add this check on frontend.

**Comment by AnshulMalik** [comment]
Merged
