### ISSUE TITLE
Notifications API 

### ISSUE THREAD

**Issue by AnshulMalik** [gawdsnitkkr/techspardha-17-backend#33]
Notification APIs to be implemented (Using sockets): 

Features

-  Send notification to all under an event (Coordinator)
-  Send individual notification (Coordinator)
-  Send notification to participants in current round (Coordinator)

User might be able to do:

- Receive notification as they arrive.
- Access notification arrived when he was not online.
- Mark notification as read.

**Comment by AnshulMalik** [comment]
ping @MacBox7

**Comment by MacBox7** [comment]
Schema:
Notifications => {Id,NotificationType,Message,EventId}
UsersNotifications => {Id(User),Id(Notif),Status}
Status = Read or Not
NotificationType = Public or Private 

EndPoints:
To all : /api/event/:id/notifyall       (Generates public notification)
To single or candidates :    /api/event/:id/notify   (Candidate/s id in req body)
Receive notification : /api/user/me/notifications (Retrieves public and private notifs )
@AnshulMalik This is the suggested enhancements.
