### ISSUE TITLE
Add foreign keys for wishList router

### ISSUE THREAD

**Issue by rewanth1997** [gawdsnitkkr/techspardha-17-backend#36]
I forgot how to create foreign keys so someone please add foreign keys for this router.
1.  LectureId is associated with GuestLectures(Id)
2.  StudentId is associated with Students(Id)

I'm unable to make the setup on my laptop due to FULLTEXT error. So someone please check the guestLectures and wishlist routers which are in rewanth branch.

**Comment by AnshulMalik** [comment]
#37 Resolves this issue
