### ISSUE TITLE
Team Names

### ISSUE THREAD

**Issue by MacBox7** [gawdsnitkkr/techspardha-17-backend#50]
A single Team is to be maintained which can register for all events.
The previous implementation keeps unique team for every event.

**Comment by rewanth1997** [comment]
Bull shit!!! Why don't we use the previous implementation. Its fine to have a unique team for every event. Students tend to keep changing team names based on the event they are willing to participate in and I don't think its mandatory to fix this issue. Instead we could checkout for something else. Am I clear?
